---
platform: linux
image_resource:
  type: docker-image
  source: {repository: node}
inputs:
  - name: agapp
    path: agapp
  - name: buildagapp
outputs:
  - name: buildagapp
    path: agapp/target
run:
  path: bash
  args: agapp/concourse/scripts/build.sh
   


  