---
resources:
  - name: agapp
    type: git
    source:
      uri: https://github.com/xdinh99z/agapp.git
      branch: master

  - name: deploy-web-app
    type: cf
    source:
      api: api.run.pivotal.io
      username: xdinh99z@gmail.com
      password: "#Join7498"
      organization: ConcourseD
      space: Globalspace
      skip_cert_check: true

jobs:
  - name: FYIagappDeloy
    public: true
    serial: true
    plan:
      - get: agapp
        trigger: true
      - task: agapptask
        file: agapp/concourse/tasks/agapptask.yml

      - put: deploy-web-app
        params:
          manifest: agapp/mainfest.yml
          path: dist/agapp