---
platform: linux
image_resource:
  type: docker-image
  source: {repository: node}
inputs:
  - name: agapp
    path: agapp
#outputs:
#  - name: deploy-web-app
#    path: agapp/dist/agapp
run:
  path: bash
  args: agapp/concourse/scripts/build.sh
