---
platform: linux
image_resource:
  type: docker-image
  source: {repository: node}
inputs:
  - name: buildagapp

- put: deploy-web-app
    params:
     manifest: buildagapp
     path: buildagapp/manifest.yml
  